# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: 6f808e778acd3fd274e48ae608c5925eb3797d912c41efd41226ea2739319bd24b4c65fc8dbf663ffa2a7c77473a23f51cb28105099aa679d9fa0321934ec444

test:
  secret_key_base: 4dcfa19fff88ec643ce52c782c93f9306a2118a31f71309868fbcb6c69e938be8a8b36aeb37db001fe48921eee9cf18328f583b0c02bf066689d78e8d4922de7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
